1. Buatlah sebuah array 1 dimensi (vektor) yang diisi dengan 36 elemen. Isi dari array
tersebut adalah bilangan random yang dibangkitkan dari rentang nilai 1 hingga 100.
Simpan array tersebut dalam sebuah variable bernama myArray, kemudian coba
tampilkan!

In [49]:
import numpy as np

# Membangkitkan array satu dimensi dengan 36 elemen, isi dari rentang 1 hingga 100
myArray = np.random.randint(1, 101, 36)

# Menampilkan array
print("myArray:", myArray)


myArray: [ 74  45  64  75  28  86  57  44  26   9  97  63  48  13   1  22   3  56
  19  65  30 100  26  10  32  65   4  14  43  12  68  51  23  36  40  19]


2. Dari myArray, bentuklah 3 array dengan bentuk yang berbeda 
(mengganti dimensi matriksnya) dengan kombinasi ukuran yang berbeda beda!

• Matriks berukuran 2x18

In [50]:
# Bentuk ulang array menjadi array 2 dimensi dengan bentuk (2x5)
matrix_2x18 = myArray.reshape(2, 18)

# Menampilkan array
print("Matrix 2x18:\n", matrix_2x18)

Matrix 2x18:
 [[ 74  45  64  75  28  86  57  44  26   9  97  63  48  13   1  22   3  56]
 [ 19  65  30 100  26  10  32  65   4  14  43  12  68  51  23  36  40  19]]


• Matriks berukuran 9x4

In [55]:
# Bentuk ulang array menjadi array 2 dimensi dengan bentuk (9x4)
matrix_9x4 = myArray.reshape(9, 4)

# Menampilkan array
print("Matrix 9x4:\n", matrix_9x4)

Matrix 9x4:
 [[ 74  45  64  75]
 [ 28  86  57  44]
 [ 26   9  97  63]
 [ 48  13   1  22]
 [  3  56  19  65]
 [ 30 100  26  10]
 [ 32  65   4  14]
 [ 43  12  68  51]
 [ 23  36  40  19]]


• Array 3 Dimensi berukuran 2x6x3

In [51]:
# Bentuk ulang array menjadi array 3 dimensi dengan bentuk (2x6x3)
matrix_2x6x3 = myArray.reshape(2, 6, 3)

# Menampilkan array
print("Matrix 2x6x3:\n", matrix_2x6x3)

Matrix 2x6x3:
 [[[ 74  45  64]
  [ 75  28  86]
  [ 57  44  26]
  [  9  97  63]
  [ 48  13   1]
  [ 22   3  56]]

 [[ 19  65  30]
  [100  26  10]
  [ 32  65   4]
  [ 14  43  12]
  [ 68  51  23]
  [ 36  40  19]]]


3. Berapakah nilai minimun dan maksimum dari myArray? Tampilkan dan coba perlihatkan
nilai maksimum dan minimum tersebut ada pada indeks keberapa!

In [56]:
# Menemukan nilai minimum dan maksimum beserta indeksnya
min_value = np.min(myArray)
max_value = np.max(myArray)
min_index = np.argmin(myArray)
max_index = np.argmax(myArray)

# Menampilkan nilai dan index minimum dan maksimum array
print("\nNilai minimum:", min_value, "pada indeks:", min_index)
print("Nilai maksimum:", max_value, "pada indeks:", max_index)



Nilai minimum: 1 pada indeks: 14
Nilai maksimum: 100 pada indeks: 21


4. Buatlah sebuah array baru dari myArray dengan data yang diambil berasal dari index 3,
5, 30, 12, 15, 8, 24, 14, 22. Setelah itu, reshape bentuknya menjadi sebuah matrix
ukuran 3x3!

In [53]:
# Mengambil data dari indeks tertentu
selected_indices = [3, 5, 30, 12, 15, 8, 24, 14, 22]
newArray = myArray[selected_indices]

# Menampilkan array baru
print("\nnewArray (dari indeks tertentu):", newArray)

# Reshape array menjadi matriks 3x3
reshapedarray = newArray.reshape(3, 3)
print("\nreshaped array 3x3):")
print(reshapedarray)


newArray (dari indeks tertentu): [75 86 68 48 22 26 32  1 26]

reshaped array 3x3):
[[75 86 68]
 [48 22 26]
 [32  1 26]]


5. Dari matrix yang dibuat pada nomor 4, tampilkan data yang nilainya lebih besar dari 50!

In [54]:
# Mendapatkan indeks elemen-elemen yang lebih besar dari 50
indices_greater_than_50 = np.where(myArray > 50)

# Menampilkan elemen-elemen yang nilainya lebih besar dari 50
print("\nElemen-elemen yang lebih besar dari 50:")
print(myArray[indices_greater_than_50])


Elemen-elemen yang lebih besar dari 50:
[ 74  64  75  86  57  97  63  56  65 100  65  68  51]


6. Buat sebuah array menggunkan salah satu method di numpy dengan output seperti di
bawah ini!

In [47]:
import numpy as np
# Membuat array dengan langkah (step) 25 dari 0 hingga 101
output_array = np.arange(0, 101, 25)

# Menampilkan array
print("output_array:", output_array)


output_array: [  0  25  50  75 100]


7. Buatlah sebuah array 2 dimensi dengan ukuran NxN di mana N nya adalah sebuah
inputan. Isi dari array tersebut seluruhnya adalah angka 8!

In [57]:
# Input nilai N dari pengguna
N = int(input("Masukkan nilai N: "))

# Membuat array 2 dimensi berukuran NxN dengan nilai 8
output_array = np.full((N, N), 8)

# Menampilkan array
print("output_array:")
print(output_array)

output_array:
[[8 8 8]
 [8 8 8]
 [8 8 8]]


8. Buatlah 2 buah array 2 dimensi seperti gambar di bawah ini, lalu simpan dalam variabel
bernama arrayA dan arrayB!

In [58]:
# Membuat array dengan rentang nilai dari 1 hingga 12
varArrayA = np.arange(1, 13)


# Bentuk ulang array menjadi array 2 dimensi dengan bentuk (3x4)
arrayA = varArrayA.reshape(3, 4)

# menampilkan array
print(arrayA)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
# Membuat array satu dimensi dengan nilai [100, 200, 300, 400]
varArrayB = np.arange(100, 401, 100)

# Mengubah bentuk array menjadi matriks 2 dimensi dengan bentuk (4, 1)
arrayB = varArrayB.reshape((4, 1))

# Menampilkan array
print(arrayB)

[[100]
 [200]
 [300]
 [400]]


Buatlah sebuah array yang berasal dari gabungan arrayA dan arrayB seperti gambar di
bawah ini, simpan dalam variabel bernama arrayC!

In [61]:
# Transposisi arrayB
arrayB_transposed = np.transpose(arrayB)

# Menggabungkan arrayA dan arrayB_transposed
arrayC = np.concatenate((arrayA, arrayB_transposed), axis=0)

# menampilkan array
print(arrayC)


[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [100 200 300 400]]


9. Dari arrayC, lakukan slicing agar menghasilkan array di bawah ini!

In [ ]:
# Melakukan pengindeksan (slicing) pada arrayC
sliced_result = arrayC[1:3, 2:4]

# menampilkan array
print("\nSliced Result:")
print(sliced_result)


Sliced Result:
[[ 7  8]
 [11 12]]


10. Dari arrayC, lakukan indexing untuk mendapatkan angka 200!

In [ ]:
# Pengindeksan yang diperbaiki untuk mendapatkan nilai 200
value_200 = arrayC[3, 1]

print("\nNilai 200 dari arrayC:")
print(value_200)


Nilai 200 dari arrayC:
200
