In [10]:
import numpy as np

# Membangkitkan array satu dimensi dengan 36 elemen, isi dari rentang 1 hingga 100
myArray = np.random.randint(1, 101, 36)

# Menampilkan array
print("myArray:", myArray)


myArray: [92 38 61 34 69 10 83 81 90 51 34 34 33 61 22 83 82 35 33 65 72 61 34 59
 34 11 52 56 61  5 19 38 37 86 49 73]


In [5]:
# Bentuk ulang array menjadi array 2 dimensi dengan bentuk (2x5)
matrix_2x18 = myArray.reshape(2, 18)

# Menampilkan array
print("Matrix 2x18:\n", matrix_2x18)

Matrix 2x18:
 [[97  8 17 28 96 41 12 17 28 13 22 33 39 27 21 47 93 72]
 [ 3 55 68 22  8 80 91 50 72 88 25 73 65 28 87 73 27 25]]


In [8]:
# Bentuk ulang array menjadi array 3 dimensi dengan bentuk (2x6x3)
matrix_2x6x3 = myArray.reshape(2, 6, 3)

# Menampilkan array
print("Matrix 2x6x3:\n", matrix_2x6x3)

Matrix 2x6x3:
 [[[97  8 17]
  [28 96 41]
  [12 17 28]
  [13 22 33]
  [39 27 21]
  [47 93 72]]

 [[ 3 55 68]
  [22  8 80]
  [91 50 72]
  [88 25 73]
  [65 28 87]
  [73 27 25]]]


In [9]:
# Mendapatkan nilai minimum dan maksimum dari array
min_value = np.min(myArray)
max_value = np.max(myArray)

# Menampilkan nilai minimum dan maksimum
print("\nNilai minimum:", min_value)
print("Nilai maksimum:", max_value)


Nilai minimum: 3
Nilai maksimum: 97


In [12]:
# Mengambil data dari indeks tertentu
selected_indices = [3, 5, 30, 12, 15, 8, 24, 14, 22]
newArray = myArray[selected_indices]

# Menampilkan array baru
print("\nnewArray (dari indeks tertentu):", newArray)

# Reshape array menjadi matriks 3x3
reshapedarray = newArray.reshape(3, 3)
print("\nreshaped array 3x3):")
print(reshapedarray)


newArray (dari indeks tertentu): [34 10 19 33 83 90 34 22 34]

reshaped array 3x3):
[[34 10 19]
 [33 83 90]
 [34 22 34]]


In [16]:
# Mendapatkan indeks elemen-elemen yang lebih besar dari 50
indices_greater_than_50 = np.where(myArray > 50)

# Menampilkan elemen-elemen yang nilainya lebih besar dari 50
print("\nElemen-elemen yang lebih besar dari 50:")
print(myArray[indices_greater_than_50])


Elemen-elemen yang lebih besar dari 50:
[97 96 93 72 55 68 80 91 72 88 73 65 87 73]


In [8]:
import numpy as np
# Membuat array dengan langkah (step) 25 dari 0 hingga 101
output_array = np.arange(0, 101, 25)

# Menampilkan array
print("output_array:", output_array)


output_array: [  0  25  50  75 100]


In [7]:
# Input nilai N dari pengguna
N = int(input("Masukkan nilai N: "))

# Membuat array 2 dimensi berukuran NxN dengan nilai 8
output_array = np.full((N, N), 8)

# Menampilkan array
print("output_array:")
print(output_array)

output_array:
[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [1]:
# Membuat array dengan rentang nilai dari 1 hingga 12
varArrayA = np.arange(1, 13)


# Bentuk ulang array menjadi array 2 dimensi dengan bentuk (3x4)
arrayA = varArrayA.reshape(3, 4)

# menampilkan array
print(arrayA)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# Membuat array satu dimensi dengan nilai [100, 200, 300, 400]
varArrayB = np.arange(100, 401, 100)

# Mengubah bentuk array menjadi matriks 2 dimensi dengan bentuk (4, 1)
arrayB = varArrayB.reshape((4, 1))

# Menampilkan array
print(arrayB)

[[100]
 [200]
 [300]
 [400]]


In [3]:
import numpy as np
# Transposisi arrayB
arrayB_transposed = np.transpose(arrayB)

# Menggabungkan arrayA dan arrayB_transposed
arrayC = np.concatenate((arrayA, arrayB_transposed), axis=0)

# menampilkan array
print(arrayC)


[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [100 200 300 400]]


In [108]:
# Melakukan pengindeksan (slicing) pada arrayC
sliced_result = arrayC[1:3, 2:4]

# menampilkan array
print("\nSliced Result:")
print(sliced_result)


Sliced Result:
[[ 7  8]
 [11 12]]


Dari arrayC, lakukan indexing untuk mendapatkan angka 200!

In [5]:
value_200 = arrayC[3, 1]
print("\nNilai 200 dari arrayC:")
print(value_200)


Nilai 200 dari arrayC:
200
